language: java
jdk:
- oraclejdk8
services:
- docker
script:
- sh gradlew check
- sh gradlew codeCoverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: releases
  api_key:
    secure: k9YLRYYUfMkdF65wC7jD3o2cEq6L/PJTJGeceoOlz8wito5BaUd+4udmZagd7YaSG7mE4uM97VRvsaqhtEMkkMdQQHjRY8AnDsKIRZwzOG6g6aID4ujDOrJXVpD7djj73r4MigwICuNkFSFQF1UC2mjCFfYJGy6RaLKbePGitXG2gUG858y3e38V3EwVDXXUcfBKJmgoB8kXQFbw8/Z7sxs/E9coBq1KGryC+7Jr4sOS/FNkYPj3+s16gGKb/zSD6mLK4yvtd5iNozmIhktocggC2qFpwm/J/vv7pU+ilaKS7rOtUTeK9mS81zQYZdyYv2YJhgXehQ0WQA32QB3U2RDPsCzP/hSG4dgeIeZTgljKgnzHvFNEmPoo1FhvzHUpMN2wXQv36b9lOmW5zz3xo5DqjN9kIwDrHePtF8/b5qhDjrA7Lu45nCmwi6wgDuqyJPX3ilA3tj73JidynSr5Y1QUXRzc2R184mXftEp4nr09NLce9jysgtU/A9L6wsynufckaqUcQlCWeErQVcdL3xYig7UxrkQUe+OzlaMYDy8sdSarOtVmqK9xePbdn3jQ2y2PEp8rIHz6pcUOwSfwiGx7vqbVYoQrDWiZzQEcZGpKa/mdcBP/ShcsxDZmmCNfgSLxkkW9sW5vSxG3Tj/mTl675GHLUIIN7v8bmFtVjzw=
  file:
  - services/core/build/libs/core-exec.jar
  - services/email/build/libs/email-exec.jar
  - services/monitor/build/libs/monitor-exec.jar
  - services/rates/build/libs/rates-exec.jar
  - services/kyc/build/libs/kyc-exec.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^(.*)-(release|beta)$"
- provider: script
  script: export ICONATOR_DOCKER_VERSION=$TRAVIS_TAG && sh docker/docker_push.sh
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^(.*)-(release|beta)$"
- provider: script
  script: export ICONATOR_DOCKER_IMAGE_NAME=master && sh docker/docker_push.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: X9lXVsLnAM7H7nUvmsk9gDJbeOlSXcNCqGCARNwOBfi4mqosdQesZnX4CHVrlKtF/97HoeCt6OtDS0njd5um5iDGXWaT3HMSI6NXPM8s0dg9PXCAlTmdgC+WU5GIx6DUMbzSRlLToLDjqdl0Du95LZRwPiBez1iRDNWOwqfcIcsIlmTAhkhx5TatlD44o72bU3oFN5/4cKFlHaaRBJcNdMexnRC4jUKPAOpfL3O+s9Aks3N29Hcb/MrGg/Fgqxfu3+t6NcLXY7o/zGnGyBU3y9OqE/WvmiqKoQaoNYrzHkmHx2NubpXG9n7JmvuEkNrqnBeOCAFEm+M1a0uf/chueJEBRZS0enbO3ddnfDmVzJbqO/XEc7OSSMTaDBgsIRMDtGaTEbHxB0D/v7N/jVihpOL06Wj/gTPa9P0sBVAfBiGIwUAXtJABv2VBkHD/Z5GjvbFPYB8i2I4OpogBElpVnqDqYfst9cXpEVEDsWfcU0zsohpprfvB6QjnnkUypLNJak6wE3FPiUAMPJIXBEDe7BRzvqdzzkvlllvrNHAA0R1eu8DMl+qedquyVQbUENdeOD7JI5o/wyKjBTegasDG6+Bg8kvdXvK7dQuuprfkJVXGi4HOL72zL4J/WNGzTdMfMEPrkQS0JcPswUaxCZTxhSxEXdu8wcaQ8o0Bn+zzPmQ=
