language: java
jdk:
- oraclejdk8
services:
- docker
script:
- sh gradlew check
- sh gradlew codeCoverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: releases
  api_key:
    secure: ZoYJCmv9FEnZUF2vP2e8C4QXIgJzSVL1BRJmhdEEgFFxjVHqZtE9a0KFCBPbVbK7dnePGrA4lE0z3gUoBQWBqQCtSW1OzQLa4esmgbWDWv7+wpjihUbIF5PLzunpuAwvVK0PO8f/CO7+Z4y7L2Ddfo+FLapfnIG9mZcCnqbz58+rMSy/I5GHMP5accuA4dDOhsHLlPDIlg3xxz6xT/Pl8cS8DRQdEsfhEtWHDpkjfqcTheMbfOv8gZ9Ysyj2AQOijEvk5ERjr3X7oydA6oK5m4vnlH2FGtz4YoXr5F89UJsEmueI8Mnuv0yUlq7vJZ2QIfxZ2f8G3E86v7Jj6efE9sXkgiN17ThnT0W/Aqo4ezss1IhnvrD0u83tD1hOhr244Ja1CkHwN1JC8LIFt02oQ4CJz8qm0vopPGQW2c3sUyvpuBnEyCzJcY6kVqiXUBRX7BD2KsSxIw5/RHlUjfX4iRR/mIiA0A5ENUTvvwSCo3LRXxb+Bd6eWQmouLwC2PZUDCJ6CAZjZozjJLIFBJsrJBRrNXbbXMpUI6H9aU/Fw7Hfjqlh+UrsFGW86lVlnBj4W1gXtH+TfjgibpEoPo9dLOGWQrwE4G/yH0xqYgN3FbTg/P2Ku5Uu8jgdAud1cIIV2fSK4cKwM98QhITIDUqPSa3PjJtXusYZdLYgSuf6hU0=
  file:
  - services/core/build/libs/core-exec.jar
  - services/email/build/libs/email-exec.jar
  - services/monitor/build/libs/monitor-exec.jar
  - services/rates/build/libs/rates-exec.jar
  - services/kyc/build/libs/kyc-exec.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^(.*)-(release|beta)$"
- provider: script
  script: export ICONATOR_DOCKER_VERSION=$TRAVIS_TAG && sh docker/docker_push.sh
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^(.*)-(release|beta)$"
- provider: script
  script: export ICONATOR_DOCKER_IMAGE_NAME=master && sh docker/docker_push.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: Qdh5yjekYRT09G+TIpLApJAEijbdTkOcuEooJnzFHN2Sb0inNBT7J35M5F6ajQAbryw+jWSxqfRuidbU8XyYskzeYFVwL45QYsjHRuVZm/JDbWm80MOa7UO0fvrb4TX+zSbZh6CQGhbuz0GPmmX444SXRyq07MfwcDkzbcLE9YLFPjEi13VlW5fMN8Vj6CzsOU1N7mWKY95cuDjGxtpUgEzLkY3NLwm6I/xR6B5f0HQ2bJ2bl3+ekW3IgTFuqCLa5IhtOPcbmrmDQQUJyg5vwWJF9KtIGBDRQwa7RRiX/HWyv/vPC84YG3XnZUTvl456mCxQw3X7V0gxr/WKw72nPdJQO+DNXMIo+FtzIdBdBDksux0hWMbn/LxWkLesWzaMfQd1dt+eHurIaEsTYyO3soX6SxatveWq0pIG2iGy5wIMBNshcVqzL5qAUHHkHfBGFwFSWRL5FbiOrnP1chgPVJMQEmsRp5Q810bodaNjWU32aBMES5xgFzviuh+ue8ux+Yks2ANBUXsDsR+bHbWiIiZpzcR3/17yBRkfRRwSJLj9k7OLthaZT3ANe6krGnmvwhEDe3XGWT7MwVvh0vcLnnXK/ZEOrNVdBLX+itJGeVGQZEhc32DNNhyS46vVu5lviSuVyXTouR7SEckrvM625Ayq7IRAml2L6k/9R2yUzd4=
