package io.iconator.commons.mailservice;

public enum MailType {

    WARNING_ADMIN_EMAIL,
    CONFIRMATION_EMAIL,
    SUMMARY_EMAIL,
    TRANSACTION_RECEIVED_EMAIL,
    TOKENS_ALLOCATED_EMAIL,
    KYC_START_EMAIL,
    KYC_REMINDER_EMAIL

}
